Repository TeamOTL/OTL, pull requests merged in 2024-05, with the labels that each got.

#18 모달 버튼전체 생성
  src/main/resources/static/index.html
  src/main/resources/static/index_kim.html
  src/main/resources/static/studyRoom.html
Labels: 개발, 수정, 프론트

#20 스터디방 html, 스터디방 방장 html 완료
  src/main/resources/static/studyRoom_maneger_yu.html
  src/main/resources/static/studyRoom_yu.html
Labels: 수정, 프론트

#24 feat/ domain 작성
  .gradle/8.7/executionHistory/executionHistory.bin
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  build.gradle
  build/resources/main/application.properties
  build/tmp/compileJava/compileTransaction/stash-dir/MemberStudy$MemberStudyBuilder.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/MemberStudy.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/Study$StudyBuilder.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/Study.class.uniqueId2
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/otl/otl/config/RootConfig.java
  src/main/java/com/otl/otl/config/SwaggerConfig.java
  src/main/java/com/otl/otl/controller/BoardController.java
  src/main/java/com/otl/otl/controller/advice/CustomRestAdvice.java
  src/main/java/com/otl/otl/domain/BaseEntity.java
  src/main/java/com/otl/otl/domain/Board.java
  src/main/java/com/otl/otl/domain/Category.java
  src/main/java/com/otl/otl/domain/Interests.java
  src/main/java/com/otl/otl/domain/LogFeedback.java
  src/main/java/com/otl/otl/domain/Member.java
  src/main/java/com/otl/otl/domain/MemberInterests.java
  src/main/java/com/otl/otl/domain/MemberStudy.java
  src/main/java/com/otl/otl/domain/Reply.java
  src/main/java/com/otl/otl/domain/Study.java
  src/main/java/com/otl/otl/domain/StudyLog.java
  src/main/java/com/otl/otl/domain/Todolist.java
  src/main/java/com/otl/otl/domain/WeeklyTask.java
  src/main/resources/application.properties
Labels: 데이터베이스

#26 studyRoom 방장 참가신청 html 재업로드
  src/main/resources/static/studyRoom_request_yu.html
Labels: 수정

#27 studyRoom 방장 참가신청 html 재재업로드
  src/main/resources/static/studyRoom_request_yu.html
Labels: 수정

#32 feat/ dashboard-calendar
  src/main/resources/static/index.html
  src/main/resources/static/js/index.global.js
Labels: 프론트

#33 Feat/ html
  src/main/resources/static/board.html
  src/main/resources/static/sidebar.js
Labels: 프론트

#38 로그인 오류 수정
  .gradle/8.7/executionHistory/executionHistory.bin
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/resources/main/templates/index.html
  build/resources/main/templates/main.html
  build/tmp/compileJava/compileTransaction/stash-dir/MemberController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/MemberStudy$MemberStudyBuilder.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/MemberStudy.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/Study$StudyBuilder.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/Study.class.uniqueId2
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/otl/otl/config/SecurityConfig.java
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/controller/UserController.java
  src/main/java/com/otl/otl/domain/Member.java
  src/main/java/com/otl/otl/repository/MemberRepository.java
  src/main/java/com/otl/otl/service/KakaoOAuth2UserService.java
  src/main/java/com/otl/otl/service/MemberService.java
  src/main/java/com/otl/otl/service/MemberServiceImpl.java
  src/main/resources/static/index_original.html
  src/main/resources/static/js/studyRecruit.js
  src/main/resources/static/js/studyRecruit1.js
  src/main/resources/templates/index.html
  src/main/resources/templates/main.html
Labels: 개발, 수정, 에러 수정, 머지에러

#44 feat/ study관련 엔티티 클래스 수정
  src/main/java/com/otl/otl/domain/BaseEntity.java
  src/main/java/com/otl/otl/domain/Category.java
  src/main/java/com/otl/otl/domain/Interests.java
  src/main/java/com/otl/otl/domain/Log.java
  src/main/java/com/otl/otl/domain/LogFeedback.java
  src/main/java/com/otl/otl/domain/Member.java
  src/main/java/com/otl/otl/domain/MemberStudy.java
  src/main/java/com/otl/otl/domain/Study.java
  src/main/java/com/otl/otl/domain/StudyInterests.java
  src/main/java/com/otl/otl/domain/Task.java
Labels: 데이터베이스

#45 로그인완료 + 게시판 글작성 완료
  build.gradle
  build/resources/main/static/js/component/topbar.js
  build/resources/main/templates/board.html
  build/resources/main/templates/main.html
  build/tmp/compileJava/compileTransaction/stash-dir/MemberController.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/otl/otl/OtlApplication.java
  src/main/java/com/otl/otl/config/SecurityConfig.java
  src/main/java/com/otl/otl/controller/BoardController.java
  src/main/java/com/otl/otl/controller/LoginController.java
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/domain/BaseEntity.java
  src/main/java/com/otl/otl/domain/Board.java
  src/main/java/com/otl/otl/dto/BoardDTO.java
  src/main/java/com/otl/otl/repository/BoardRepository.java
  src/main/java/com/otl/otl/repository/search/BoardSearch.java
  src/main/java/com/otl/otl/service/BoardService.java
  src/main/java/com/otl/otl/service/BoardServiceImpl.java
  src/main/resources/static/js/component/topbar.js
  src/main/resources/templates/board.html
  src/main/resources/templates/main.html
Labels: 개발, 프론트, 백엔드, 데이터베이스

#47 게시판/게시글생성모달창 컴포넌트 생성
  src/main/java/com/otl/otl/config/SwaggerConfig.java
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/resources/static/img/plus.svg
  src/main/resources/static/js/component/boardCreateModal.js
  src/main/resources/templates/board.html
Labels: 프론트

#48 feat/study 의 dday 계산 추가 & 로그 패키지명 수정
  src/main/java/com/otl/otl/domain/Study.java
  src/main/java/com/otl/otl/repository/StudyRepository.java
  src/main/java/com/otl/otl/service/StudyService.java
  src/main/java/com/otl/otl/service/StudyServiceImpl.java
  src/main/resources/application.properties
Labels: 수정, 백엔드

#53 gitignore bin 디렉토리 추가
  .gitignore
Labels: 수정, 핫픽스

#54 게시판/게시글조회모달창 생성
  src/main/resources/static/js/component/boardReadModal.js
  src/main/resources/templates/board.html
  src/test/java/com/otl/otl/repository/BoardRepositoryTests.java
  src/test/java/com/otl/otl/service/BoardServiceTests.java
Labels: 프론트

#58 swagger ui update
  build.gradle
  src/main/java/com/otl/otl/config/SwaggerConfig.java
  src/main/java/com/otl/otl/controller/DashBoardController.java
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/domain/Study.java
  src/main/resources/application.properties
  src/main/resources/static/js/component/todoList.js
  src/main/resources/templates/dashBoard.html
  src/main/resources/templates/dashBorad.html
Labels: 수정, 라이브러리

#61 게시판/CRUD 기능 구현 완료
  build.gradle
  src/main/java/com/otl/otl/domain/Board.java
  src/main/java/com/otl/otl/dto/BoardDTO.java
  src/main/java/com/otl/otl/dto/MemberDTO.java
  src/main/java/com/otl/otl/repository/search/BoardSearch.java
  src/main/java/com/otl/otl/repository/search/BoardSearchImpl.java
  src/main/java/com/otl/otl/service/BoardService.java
  src/main/java/com/otl/otl/service/BoardServiceImpl.java
  src/test/java/com/otl/otl/repository/BoardRepositoryTests.java
  src/test/java/com/otl/otl/service/BoardServiceTests.java
Labels: 개발, 백엔드

#63 java.lang.ClassNotFoundException
  build.gradle
Labels: 수정, 핫픽스

#64 게시판 조회(프로필 이미지 위치 수정 전)
  src/main/java/com/otl/otl/controller/BoardController.java
  src/main/java/com/otl/otl/repository/search/BoardSearchImpl.java
  src/main/java/com/otl/otl/service/BoardServiceImpl.java
  src/main/resources/static/js/component/boardReadModal.js
  src/main/resources/templates/board.html
Labels: 개발, 프론트, 백엔드

#66 나의정보 프로필이미지 수정중
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/service/MemberService.java
  src/main/java/com/otl/otl/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/js/component/userSettingModal.js
  src/main/resources/templates/board.html
Labels: 개발, 수정, 프론트, 백엔드, 데이터베이스

#67 TodoList mvc, dashboard,html, securityConfig
  src/main/java/com/otl/otl/config/SecurityConfig.java
  src/main/java/com/otl/otl/controller/DashBoardController.java
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/controller/TodolistController.java
  src/main/java/com/otl/otl/domain/Todolist.java
  src/main/java/com/otl/otl/dto/TodolistDTO.java
  src/main/java/com/otl/otl/repository/TodolistRepository.java
  src/main/java/com/otl/otl/service/TodolistService.java
  src/main/java/com/otl/otl/service/TodolistServiceImpl.java
  src/main/resources/templates/dashBoard.html
  src/test/java/com/otl/otl/repository/TodolistRepositoryTests.java
Labels: 개발, 수정, 프론트, 백엔드, 데이터베이스, 회의

#70 게시판 조회, 수정 구현 완료
  src/main/java/com/otl/otl/controller/BoardController.java
  src/main/resources/static/js/component/boardReadModal.js
  src/main/resources/templates/board.html
Labels: 개발, 수정, 프론트, 백엔드

#73 게시판 삭제 구현 완료, 게시판 수정 오류 해결 완료
  src/main/java/com/otl/otl/controller/BoardController.java
  src/main/java/com/otl/otl/repository/BoardRepository.java
  src/main/java/com/otl/otl/service/BoardServiceImpl.java
  src/main/resources/static/js/component/boardReadModal.js
Labels: 개발, 수정, 백엔드

#75 나의정보 사진저장중
  src/main/java/com/otl/otl/controller/BoardController.java
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/domain/Member.java
  src/main/java/com/otl/otl/service/MemberServiceImpl.java
  src/main/resources/static/js/component/userSettingModal.js
Labels: 개발, 수정, 프론트, 백엔드, 데이터베이스

#76 나의정보 완료
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/resources/static/js/component/topbar.js
  src/main/resources/static/js/component/userSettingModal.js
Labels: 개발, 프론트, 백엔드, 데이터베이스

#77 feat/ 엔티티 연관관계 수정
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/controller/MyStudyController.java
  src/main/java/com/otl/otl/controller/StudyController.java
  src/main/java/com/otl/otl/domain/Interests.java
  src/main/java/com/otl/otl/domain/Member.java
  src/main/java/com/otl/otl/domain/MemberInterests.java
  src/main/java/com/otl/otl/domain/MemberStudy.java
  src/main/java/com/otl/otl/domain/Study.java
  src/main/java/com/otl/otl/domain/StudyInterests.java
  src/main/java/com/otl/otl/domain/Task.java
  src/main/java/com/otl/otl/domain/taskFeedback.java
  src/main/java/com/otl/otl/dto/CategoryDTO.java
  src/main/java/com/otl/otl/dto/InterestsDTO.java
  src/main/java/com/otl/otl/dto/MemberStudyDTO.java
  src/main/java/com/otl/otl/dto/StudyDTO.java
  src/main/java/com/otl/otl/dto/StudyListDTO.java
  src/main/java/com/otl/otl/dto/TaskDTO.java
  src/main/java/com/otl/otl/repository/CategoryRepository.java
  src/main/java/com/otl/otl/repository/InterestsRepository.java
  src/main/java/com/otl/otl/repository/MemberStudyRepository.java
  src/main/java/com/otl/otl/repository/MyStudyRepository.java
  src/main/java/com/otl/otl/repository/StudyRepository.java
  src/main/java/com/otl/otl/repository/TaskRepository.java
  src/main/java/com/otl/otl/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/otl/otl/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/otl/otl/service/MYStudyServiceImpl.java
  src/main/java/com/otl/otl/service/MyStudyService.java
  src/main/java/com/otl/otl/service/StudyService.java
  src/main/java/com/otl/otl/service/StudyServiceImpl.java
  src/main/resources/static/js/component/studyCreateModal.js
Labels: 개발, 백엔드, 데이터베이스, 엔티티

#80 대시보드 기능 사라진 내용 추가
  README.md
  src/main/java/com/otl/otl/controller/DashBoardController.java
  src/main/java/com/otl/otl/controller/StudyController.java
  src/main/java/com/otl/otl/controller/TodolistController.java
  src/main/java/com/otl/otl/domain/Member.java
  src/main/java/com/otl/otl/domain/Todolist.java
  src/main/java/com/otl/otl/repository/TaskRepository.java
  src/main/java/com/otl/otl/repository/TodolistRepository.java
  src/main/java/com/otl/otl/service/TaskService.java
  src/main/java/com/otl/otl/service/TaskServiceImpl.java
  src/main/java/com/otl/otl/service/TodolistService.java
  src/main/java/com/otl/otl/service/TodolistServiceImpl.java
  src/main/resources/templates/dashBoard.html
  src/main/resources/templates/todo.html
  src/test/java/com/otl/otl/repository/MemberStudyRepositoryTests.java
  src/test/java/com/otl/otl/repository/TodolistRepositoryTests.java
Labels: 에러 수정, 프론트, 백엔드, 데이터베이스, 핫픽스

#81 Feat/ memberstudy repositroy
  src/main/java/com/otl/otl/domain/Interests.java
  src/main/java/com/otl/otl/domain/MemberStudy.java
  src/main/java/com/otl/otl/domain/Study.java
  src/main/java/com/otl/otl/domain/Task.java
  src/main/java/com/otl/otl/dto/MemberStudyProjection/MemberStudyProjection.java
  src/main/java/com/otl/otl/dto/MemberStudyProjection/MemberStudyProjectionImpl.java
  src/main/java/com/otl/otl/dto/StudyListDTO.java
  src/main/java/com/otl/otl/dto/TaskDTO.java
  src/main/java/com/otl/otl/repository/MemberStudyRepository.java
  src/main/java/com/otl/otl/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/otl/otl/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/otl/otl/service/MemberStudyService.java
  src/main/java/com/otl/otl/service/MemberStudyServiceImpl.java
  src/main/java/com/otl/otl/service/converter/CustomConverters.java
  src/test/java/com/otl/otl/repository/MemberStudyRepositoryTests.java
  src/test/java/com/otl/otl/repository/StudyRepositoryTests.java
Labels: 개발, 백엔드, 데이터베이스

#82 게시판 검색, 댓글 등록/삭제 구현 완료
  src/main/java/com/otl/otl/controller/BoardController.java
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/controller/ReplyController.java
  src/main/java/com/otl/otl/dto/ReplyDTO.java
  src/main/java/com/otl/otl/repository/BoardRepository.java
  src/main/java/com/otl/otl/repository/ReplyRepository.java
  src/main/java/com/otl/otl/repository/search/BoardSearch.java
  src/main/java/com/otl/otl/repository/search/BoardSearchImpl.java
  src/main/java/com/otl/otl/service/BoardService.java
  src/main/java/com/otl/otl/service/BoardServiceImpl.java
  src/main/java/com/otl/otl/service/ReplyService.java
  src/main/java/com/otl/otl/service/ReplyServiceImpl.java
  src/main/resources/static/js/board.js
  src/main/resources/static/js/component/boardReadModal.js
  src/main/resources/templates/board.html
  src/test/java/com/otl/otl/service/ReplyServiceTests.java
Labels: 개발, 수정, 프론트, 백엔드

#84 나의스터디룸 구현중
  src/main/java/com/otl/otl/controller/BoardController.java
  src/main/java/com/otl/otl/controller/MemberController.java
  src/main/java/com/otl/otl/domain/Member.java
  src/main/java/com/otl/otl/domain/Study.java
  src/main/java/com/otl/otl/dto/StudyDTO.java
  src/main/java/com/otl/otl/dto/StudyListDTO.java
  src/main/java/com/otl/otl/repository/MemberStudyRepository.java
  src/main/java/com/otl/otl/service/MemberService.java
  src/main/java/com/otl/otl/service/MemberServiceImpl.java
  src/main/java/com/otl/otl/utils/ImageUtils.java
  src/main/resources/static/js/component/boardReadModal.js
  src/main/resources/static/js/component/topbar.js
  src/main/resources/templates/studyRoom_yu.html
Labels: 개발, 프론트, 백엔드, 데이터베이스, 엔티티

#85 게시판, 댓글 구현 완료
  src/main/java/com/otl/otl/controller/ReplyController.java
  src/main/java/com/otl/otl/repository/ReplyRepository.java
  src/main/java/com/otl/otl/service/ReplyService.java
  src/main/java/com/otl/otl/service/ReplyServiceImpl.java
  src/main/resources/static/js/component/boardReadModal.js
  src/test/java/com/otl/otl/repository/MemberStudyRepositoryTests.java
Labels: 개발, 수정, 프론트, 백엔드

#89 StudyService->StudyServiceImpl
  src/main/java/com/otl/otl/service/StudyService.java
  src/main/java/com/otl/otl/service/StudyServiceImpl.java
Labels: 수정
